language: objective-c
osx_image: xcode7.2
xcode_project: KeenClient.xcodeproj
xcode_scheme: KeenClient
xcode_sdk: iphonesimulator9.2
before_install:
  - gem install bundler
  - rvm use $RVM_RUBY_VERSION
  - brew update
  - brew outdated xctool || brew upgrade xctool
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: bundle exec slather
script: ./bin/test.sh
